### ISSUE TITLE
在无网络下播放失败，重试，会出现signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#1186] opened 2016-04-17 09:41 UTC
********** Crash dump: **********
Build fingerprint: 'samsung/ja3gzs/ja3g:4.4.2/KOT49H/I9500ZSUDNK1:user/release-keys'
pid: 6521, tid: 6595, name: ff_read  >>> tv.danmaku.ijk.media.player:ijk <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
Stack frame I/DEBUG   (22333):     #00  pc 000117d0  /system/lib/libc.so (dlfree+1191): Routine ??
??:0
Stack frame I/DEBUG   (22333):     #01  pc 0000dd1f  /system/lib/libc.so (free+10): Routine ??
??:0
Stack frame I/DEBUG   (22333):     #02  pc 0014ec63  /data/app-lib/tv.danmaku.ijk.media.player-12/libijkffmpeg.so (ffurl_closep+82): Routine ffurl_closep at /home/lyq/git/ijkplayer-d0413/ijkplayer/android/contrib/ffmpeg-armv7a/libavformat/avio.c:476
Crash dump is completed
就是
av_freep(&h->priv_data);这个方法

**Comment by lyqaiym** [comment] 2016-04-17 10:09
去年的版本，一直没问题，最近更新了，发现这个问题了

**Comment by Android4MediaPlayer** [comment] 2016-04-17 12:25
什么版本？

**Comment by lyqaiym** [comment] 2016-04-17 12:47
就是新下载的，失败以后，重新new一个IJKPlayer，就报错了，fault addr deadbaad，但是&h->priv_data的地址还不是deadbaad，

**Comment by Android4MediaPlayer** [comment] 2016-04-17 13:00
必现还是跟机型有关

**Comment by lyqaiym** [comment] 2016-04-17 13:01
没试其他机型，去年的版本在手机上都没事，

**Comment by Android4MediaPlayer** [comment] 2016-04-17 13:08
我上班再看下0.5.0版本

**Comment by bbcallen** [comment] 2016-04-18 03:04
I'll take look.

**Comment by wanzhi** [comment] 2016-04-18 03:51
We look forward to fix this bug as soon as possible

**Comment by bbcallen** [comment] 2016-04-18 04:20
Did you reproduce this problem in demo, on in your own app?

**Comment by wanzhi** [comment] 2016-04-18 04:39
1, in the demo, I used to use master translation of the support https armv7a so, this appears to play random error of http or https when hls
2, in the demo, I use compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.5.0', http playback of hls, the random error
3, in the demo, I use compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.4.5.1', playing the http hls, not wrong

**Comment by bbcallen** [comment] 2016-04-18 04:41
How did you "重试"?

**Comment by wanzhi** [comment] 2016-04-18 04:44
They were tested different VideoUri and gradle dependencies

**Comment by bbcallen** [comment] 2016-04-18 04:45
I mean "在无网络下播放失败，重试，会出现signal 11"

**Comment by wanzhi** [comment] 2016-04-18 04:48
Sorry, I was wrong always in the presence of network conditions occur

**Comment by lyqaiym** [comment] 2016-04-21 03:15
@bbcallen @wanzhi 我好像知道是哪个变量了。是tcp协议的libavformat/tcp.c下的typedef struct TCPContext的AVApplicationContext *app_ctx;我还不知道有啥用，但是我去掉，就没事了
在无网络下，总是走到这个协议的时候，挂了

**Comment by bbcallen** [comment] 2016-04-21 03:35
Sounds like you didn't clean and rebuild FFmpeg after a git pull.

**Comment by lyqaiym** [comment] 2016-04-22 01:41
@bbcallen 怎么解决啊，不是我一个人有着问题，有时候有网播放hls，释放的时候也会crash

**Comment by bbcallen** [comment] 2016-04-22 03:16
No, I still can't reproduce here.

Did you reproduce this problem in demo, on in your own app?
Did you clean and rebuild FFmpeg after a git pull?

**Comment by ielicyan** [comment] 2016-04-22 04:19
I followed the usage steps on "https://github.com/bbcallen/ijkplayer" and came across the sample issue.

**Comment by bbcallen** [comment] 2016-04-22 06:32
Can not reproduce on Nexus 6p, Android 6.0.1.
Do you have any idea about the difference between your test env and my test env?

**Comment by lyqaiym** [comment] 2016-04-22 06:58
我用三星s4，必现，在vivo，5.0就没事

**Comment by wanzhi** [comment] 2016-04-22 07:08
0.5.0 is always signal 11 (SIGSEGV) so cut everything back to normal 0.4.5.1

**Comment by ielicyan** [comment] 2016-04-22 07:19
My test phone is Huawei Honor-7.

**Comment by bbcallen** [comment] 2016-04-25 02:41
I'll see if I can get such devices.

**Comment by bbcallen** [comment] 2016-04-26 03:53
Possibly fixed in k0.5.1

**Closed** 2016-07-18 08:36 UTC
Labels: can-not-reproduce
